name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
      - name: Config line ending for windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Test
        run: go test -v ./...
